import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.services': 'Services',
    'nav.blog': 'Blog',
    'nav.contact': 'Contact Us',
    'nav.book': 'Book an Appointment',
    
    // Hero
    'hero.headline': 'Dr. Paws Veterinary Clinic',
    'hero.tagline': 'Compassionate Care for Your Beloved Pets',
    'hero.subheadline': 'Providing the Highest Quality Veterinary Care',
    'hero.description': "Dr. Paws Veterinary Clinic offers cutting-edge technology in veterinary care. Through our expert team and advanced diagnostic and treatment equipment, we ensure comprehensive care from routine checkups to precise surgeries.",
    'hero.cta': 'Book Your Appointment Today',
    'hero.readMore': 'Read More',
    
    // About
    'about.headline': 'Committed to Your Pet\'s Well-being, Every Step of the Way',
    'about.description': "At Dr. Paws Veterinary Clinic, we understand the special bond you share with your pets. Our experienced and compassionate team is dedicated to providing comprehensive, high-quality veterinary care to keep your furry companions healthy and happy throughout their lives. We strive to create a comfortable and welcoming environment for both you and your pet.",
    'about.readMore': 'Read More',
    
    // Services
    'services.headline': 'What we offer?',
    'services.description': "Dr. Paws Veterinary Clinic provides a comprehensive range of services to keep your pets healthy at every stage of life. From routine checkups to advanced diagnostics and surgery, we're here for all your pet's healthcare needs.",
    'services.readMore': 'Read more',
    'services.wellness.title': 'Wellness Exams',
    'services.wellness.description': 'Comprehensive health checkups to keep your pet in optimal condition.',
    'services.emergency.title': 'Emergency Care',
    'services.emergency.description': '24/7 emergency services for urgent medical situations.',
    'services.vaccinations.title': 'Vaccinations',
    'services.vaccinations.description': 'Complete vaccination programs to protect your pets from diseases.',
    'services.surgery.title': 'Surgery',
    'services.surgery.description': 'Advanced surgical procedures with state-of-the-art equipment.',
    'services.diagnostics.title': 'Diagnostics',
    'services.diagnostics.description': 'Advanced diagnostic imaging and laboratory services.',
    'services.dental.title': 'Dental Care',
    'services.dental.description': 'Professional dental cleaning and oral health services.',
    
    // Service Packages
    'packages.headline': 'Service Packages',
    'packages.description': "Choose the perfect care package for your pet's needs. All packages include comprehensive veterinary care tailored to keep your beloved companion healthy and happy.",
    'packages.basic.name': 'Basic Care',
    'packages.basic.price': '299',
    'packages.basic.period': 'SAR/year',
    'packages.basic.feature1': 'Annual Wellness Exam',
    'packages.basic.feature2': 'Basic Vaccinations',
    'packages.basic.feature3': 'Parasite Prevention',
    'packages.basic.feature4': 'Dental Consultation',
    'packages.basic.feature5': 'Nutrition Guidance',
    'packages.complete.name': 'Complete Care',
    'packages.complete.price': '599',
    'packages.complete.period': 'SAR/year',
    'packages.complete.feature1': 'Bi-Annual Wellness Exams',
    'packages.complete.feature2': 'Complete Vaccination Package',
    'packages.complete.feature3': 'Advanced Parasite Prevention',
    'packages.complete.feature4': 'Dental Cleaning Included',
    'packages.complete.feature5': 'Blood Work & Diagnostics',
    'packages.complete.feature6': 'Emergency Care Discount',
    'packages.premium.name': 'Premium Care',
    'packages.premium.price': '999',
    'packages.premium.period': 'SAR/year',
    'packages.premium.feature1': 'Quarterly Wellness Exams',
    'packages.premium.feature2': 'Premium Vaccination Package',
    'packages.premium.feature3': 'Year-Round Parasite Prevention',
    'packages.premium.feature4': 'Professional Dental Care',
    'packages.premium.feature5': 'Comprehensive Lab Work',
    'packages.premium.feature6': 'Priority Emergency Care',
    'packages.premium.feature7': '24/7 Vet Consultation',
    'packages.popular': 'Most Popular',
    'packages.bookNow': 'Book Now',
    
    // Media
    'media.headline': 'Our Media',
    'media.description': 'Take a closer look at our state-of-the-art facilities and see how we provide exceptional care for your beloved pets in a warm and welcoming environment.',
    
    // Why Choose Us
    'why.headline': 'Why Choose Dr. Paws Veterinary Clinic?',
    'why.reason1.title': 'Comprehensive & Affectionate Care',
    'why.reason1.description': 'We treat every pet as if it were our own, with kindness, respect, and understanding.',
    'why.reason2.title': 'Experienced Team',
    'why.reason2.description': 'Our veterinarians and support staff have years of experience and are passionate about animal health.',
    'why.reason3.title': 'State-of-the-Art Facility',
    'why.reason3.description': 'We utilize advanced technology and equipment to provide the best possible care.',
    'why.reason4.title': 'Tailored Plan',
    'why.reason4.description': 'We tailor our treatment plans to meet the unique needs of each pet.',
    'why.readMore': 'Read More',
    
    // Reviews
    'reviews.headline': 'What Our Customers Say',
    'reviews.1.name': 'Ahmed Al-Rashid',
    'reviews.1.text': 'Excellent service! The staff was very caring and professional with my cat. Highly recommend Dr. Paws!',
    'reviews.2.name': 'Sarah Johnson',
    'reviews.2.text': 'My dog received the best care here. The doctors are knowledgeable and the clinic is very clean.',
    'reviews.3.name': 'Mohammed Hassan',
    'reviews.3.text': 'Great experience overall. The veterinarian explained everything clearly and my pet feels much better.',
    'reviews.4.name': 'Emily Rodriguez',
    'reviews.4.text': 'The emergency service was outstanding. They took care of my rabbit immediately and professionally.',
    'reviews.5.name': 'Khalid Abdullah',
    'reviews.5.text': 'Best veterinary clinic in Riyadh! The staff is friendly and they truly care about animals.',
    'reviews.6.name': 'Jennifer Lee',
    'reviews.6.text': 'Very impressed with the facilities and the level of care. My parrot received excellent treatment.',
    'reviews.7.name': 'Omar Saeed',
    'reviews.7.text': 'Professional team and modern equipment. They made my pet feel comfortable during the visit.',
    'reviews.8.name': 'Lisa Martinez',
    'reviews.8.text': 'Wonderful experience! The grooming service was perfect and my dog looks amazing. Thank you!',
    
    // Contact
    'contact.headline': 'Contact Us',
    'contact.subheadline': 'Contact Dr. Paws Veterinary Clinic & Schedule Your Pet\'s Appointment Today!',
    'contact.name': 'Name',
    'contact.phone': 'Phone Number',
    'contact.email': 'Email',
    'contact.message': 'Message',
    'contact.submit': 'Submit',
    'contact.success': 'Thank you! We will contact you soon.',
    
    // About Page
    'aboutPage.header': 'Dr. Paws Veterinary Care Center',
    'aboutPage.subheader': 'Expertise You Can Trust',
    'aboutPage.whoWeAre.title': 'About Dr. Paws – Who We Are',
    'aboutPage.whoWeAre.subtitle': 'Dr. Paws Veterinary Clinic: Your Partner in Pet Care',
    'aboutPage.whoWeAre.para1': 'We believe that every pet deserves a happy and healthy life. More than just a veterinary clinic, we are your partners in caring for your furry friend. Our dedicated team is committed to providing comprehensive, high-quality care, from routine check-ups to complex surgeries.',
    'aboutPage.whoWeAre.para2': 'With years of experience in veterinary care, Dr. Paws offers a wide range of services to meet all your pet\'s needs. Using the latest technology and equipment, we diagnose and treat various health conditions, ensuring your pet\'s health and well-being throughout their life. We are proud to be a trusted clinic for veterinary care in Riyadh.',
    'aboutPage.whoWeAre.para3': 'We strive to create a welcoming and comfortable environment for both you and your furry companions, making every visit a positive experience. We are proud to be a trusted veterinary care center in the Riyadh community.',
    'aboutPage.vision.title': 'Our Vision',
    'aboutPage.vision.content': 'Dr. Paws clinics strive to be the premier destination for pet care, providing the highest quality healthcare for our furry friends.',
    'aboutPage.mission.title': 'Our Mission',
    'aboutPage.mission.content': 'Our mission is to deliver compassionate, advanced veterinary care. We are committed to providing the highest quality medical services to pets, from routine check-ups to specialized treatments, all carried out by our experienced team in a caring environment.',
    'aboutPage.whyChoose.title': 'Why Choose Dr. Paws Veterinary Clinic?',
    'aboutPage.whyChoose.reason1.title': 'Compassionate Care',
    'aboutPage.whyChoose.reason1.description': 'We treat every pet as if they were our own, with kindness, respect, and understanding.',
    'aboutPage.whyChoose.reason2.title': 'Experienced Team',
    'aboutPage.whyChoose.reason2.description': 'Our veterinarians and support staff have years of experience and are passionate about animal health.',
    'aboutPage.whyChoose.reason3.title': 'State-of-the-Art Facility',
    'aboutPage.whyChoose.reason3.description': 'We utilize advanced technology and equipment to provide the best possible care.',
    'aboutPage.whyChoose.reason4.title': 'Personalized Approach',
    'aboutPage.whyChoose.reason4.description': 'We tailor our treatment plans to meet the unique needs of each pet.',
    'aboutPage.doctors.title': 'Our Doctors',
    'aboutPage.doctors.description': 'Our team of experienced and compassionate veterinarians is the heart of Dr. Paws Veterinary Care Center. They are dedicated to providing the highest standard of care and are passionate about improving the lives of animals. With diverse areas of expertise, our doctors work collaboratively to ensure your pet receives the best possible treatment.',
    'aboutPage.doctors.noInfo': 'Doctor profiles coming soon',
    'aboutPage.partners.title': 'Our Partners',
    'aboutPage.partners.noInfo': 'Partner information coming soon',
    'aboutPage.careers.title': 'Careers / Join Our Team',
    'aboutPage.careers.description': 'Looking for a rewarding career in animal health? Dr. Paws Veterinary Care Center offers exciting opportunities for professional growth and development in a dynamic and fast-paced environment.',
    'aboutPage.careers.personalInfo': 'Personal Information',
    'aboutPage.careers.fullName': 'Full Name',
    'aboutPage.careers.email': 'Email Address',
    'aboutPage.careers.phone': 'Phone Number',
    'aboutPage.careers.professionalInfo': 'Professional Information',
    'aboutPage.careers.resume': 'Resume/CV Upload',
    'aboutPage.careers.coverLetter': 'Cover Letter (Optional)',
    'aboutPage.careers.position': 'Desired Position (if known)',
    'aboutPage.careers.startDate': 'Available Start Date',
    'aboutPage.careers.experience': 'Relevant Experience',
    'aboutPage.careers.experiencePlaceholder': 'e.g., veterinary technician, veterinary assistant, receptionist',
    'aboutPage.careers.certifications': 'Veterinary Certifications (if applicable)',
    'aboutPage.careers.education': 'Education Level and Institution',
    'aboutPage.careers.interests': 'Areas of Interest',
    'aboutPage.careers.interestsPlaceholder': 'e.g., surgery, internal medicine, emergency care',
    'aboutPage.careers.submit': 'Submit Application',
    
    // Services Page
    'servicesPage.header': 'Our Services',
    'servicesPage.subheader': 'Experience exceptional veterinary care at the best pet clinic: Dr. Paws. We offer a full range of care for your pets, from routine checkups to advanced treatments.',
    'servicesPage.bookAppointment': 'Book Your Appointment Today!',
    'servicesPage.mainHeadline': 'Experience Comprehensive & Exceptional Veterinary Care at Dr. Paws, The Best Pet Clinic',
    
    'servicesPage.examinations.title': 'Periodic Medical Examinations',
    'servicesPage.examinations.description': 'At Dr. Paws, we believe preventative care is the foundation for a long and healthy life for all pets. Our periodic examinations, also known as wellness exams or routine checkups, are a vital part of our comprehensive veterinary services. These routine visits allow our veterinarians to assess your pet\'s overall health, detect potential problems early, and provide personalized recommendations for their ongoing care.',
    'servicesPage.examinations.canineTitle': 'Canine Periodic Examinations:',
    'servicesPage.examinations.canineIntro': 'During a canine periodic medical examination, we conduct a thorough physical examination, including:',
    'servicesPage.examinations.canine': 'Vital Signs: Checking temperature, pulse, and respiration rate. • Cardiopulmonary Auscultation: Listening to the heart and lungs for any abnormalities. • Ophthalmic Examination: Examining the eyes for signs of cataracts, glaucoma, or other eye diseases. • Otoscopic Examination: Checking the ears for infections, mites, or other ear problems. • Oral Examination: Assessing teeth and gums for tartar buildup, gingivitis, and other dental issues. • Dermatological Examination: Examining the skin and coat for allergies, infections, parasites, or other skin problems. • Abdominal Palpation: Gently palpating the abdomen to check for enlarged organs, masses, or other abnormalities. • Musculoskeletal Evaluation: Assessing joints and muscles for signs of arthritis, lameness, or other musculoskeletal problems.',
    'servicesPage.examinations.felineTitle': 'Feline Periodic Examinations:',
    'servicesPage.examinations.felineIntro': 'Feline periodic medical examinations are conducted with a gentle and patient approach to minimize stress on your cat. The examination includes:',
    'servicesPage.examinations.feline': 'Vital Signs: Checking temperature, pulse, and respiration rate. • Cardiopulmonary Auscultation: Listening to the heart and lungs for any abnormalities. • Ophthalmic Examination: Examining the eyes for signs of cataracts, glaucoma, or other eye diseases. • Otoscopic Examination: Checking the ears for infections, mites, or other ear problems. • Oral Examination: Assessing teeth and gums for tartar buildup, gingivitis, and other dental issues. • Dermatological Examination: Examining the skin and coat for allergies, infections, parasites, or other skin problems. • Abdominal Palpation: Gently palpating the abdomen to check for enlarged organs, masses, or other abnormalities.',
    'servicesPage.examinations.avianTitle': 'Avian Periodic Examinations:',
    'servicesPage.examinations.avianIntro': 'Avian periodic medical examinations require specialized knowledge and handling techniques. Our avian examinations include:',
    'servicesPage.examinations.avian': 'Physical Examination: Thorough assessment of feathers, beak, eyes, nares (nostrils), and listening to the heart and lungs. • Weight and Body Condition Recording: Assessing overall health and nutritional status. • Uropygial Gland Examination: Checking the oil gland for any abnormalities. • Abdominal Palpation: Gentle palpation to check for enlarged organs or other issues.',
    'servicesPage.examinations.closing': 'Regular checkups are essential for maintaining your pet\'s health and preventing serious health problems. We recommend the frequency of these examinations based on your pet\'s species, age, breed, and health history. Contact us to schedule a wellness visit for your pet and ensure they receive comprehensive veterinary services at the best pet clinic.',
    
    'servicesPage.grooming.title': 'Hygiene & Grooming Services',
    'servicesPage.grooming.description': 'Maintaining your pet\'s cleanliness and appearance significantly contributes to their overall health, comfort, and well-being. At Dr. Paws, we offer a range of effective pet hygiene clinic services designed to keep your pet looking and feeling their best. These services, while not purely medical, are an important part of preventative care and complement our other veterinary services:',
    'servicesPage.grooming.nailTrimmingTitle': 'Nail Trimming:',
    'servicesPage.grooming.nailTrimming': 'Regular nail trimming is essential to prevent overgrowth, which can cause painful discomfort, difficulty walking, and even joint problems. We provide nail trimming services for dogs, cats, and birds, using stress-minimizing techniques to ensure a comfortable experience.',
    'servicesPage.grooming.earCleaningTitle': 'Ear Cleaning:',
    'servicesPage.grooming.earCleaning': 'Clean ears are healthy ears! Our ear cleaning service helps prevent infections, remove wax buildup, and maintain your pet\'s comfort. This service is available for dogs and cats and is particularly beneficial for breeds prone to ear problems.',
    'servicesPage.grooming.bathingTitle': 'Bathing and Drying:',
    'servicesPage.grooming.bathing': 'We provide soothing bathing and drying services using high-quality, pet-safe shampoos and conditioners. This service helps remove dirt, debris, and odors, leaving your pet\'s coat clean, soft, and healthy. This service is primarily for dogs and cats and can be customized for their skin type.',
    'servicesPage.grooming.groomingTitle': 'Hair Combing and Grooming:',
    'servicesPage.grooming.grooming': 'Regular grooming, including combing and haircuts, is essential for maintaining a healthy and manageable coat. Our experienced groomers provide breed-specific haircuts and gentle detangling services, helping to prevent painful mats and skin irritation. This service is primarily for dogs and cats with long or dense fur.',
    
    'servicesPage.diagnostics.title': 'Diagnostic Tests',
    'servicesPage.diagnostics.description': 'Accurate and timely diagnosis is crucial for effective treatment. At the Dr. Paws Animal Testing Center, we provide a comprehensive range of veterinary diagnostic services to quickly and accurately assess your pet\'s health. The Dr. Paws Animal Testing Center is equipped with the latest diagnostic technology, enabling us to perform a diverse array of tests, including:',
    'servicesPage.diagnostics.labTitle': 'Laboratory Tests:',
    'servicesPage.diagnostics.lab': 'Blood Chemistry Tests: These tests assess organ function (liver, kidney, pancreas), electrolyte balance, and other important blood parameters. • Complete Blood Count: Provides information about red blood cells, white blood cells, platelets, and other blood components, helping diagnose infections, anemia, and other blood disorders. • Urinalysis: This test evaluates kidney function, detects urinary tract infections, and identifies other abnormalities of the urinary system. • Intestinal Parasite Tests: Microscopic examination of fecal samples to detect and identify intestinal parasites. • Fungal Disease Tests: Various tests, including microscopy and cultures, to diagnose fungal infections. • Viral Disease Tests: Using various diagnostic methods to detect viral infections.',
    'servicesPage.diagnostics.imagingTitle': 'Imaging:',
    'servicesPage.diagnostics.imaging': 'X-rays (Radiography): Providing detailed images of bones, joints, and internal organs. • Dental X-rays: Used specifically to assess dental health and surrounding bone structures. • Ultrasound: Using sound waves to create live images of internal organs, enabling detailed assessment of their structure and function.',
    'servicesPage.diagnostics.advancedTitle': 'Advanced Diagnostics:',
    'servicesPage.diagnostics.advanced': 'Microscopy: Examining samples (such as blood, tissues, or urine) under a microscope to identify cells, bacteria, parasites, or other abnormalities. • Internal and External Endoscopy: Using a small camera attached to a flexible tube to see inside organs or body cavities.',
    'servicesPage.diagnostics.closing': 'These comprehensive veterinary diagnostic services enable our doctors to determine the cause of your pet\'s illness or injury and develop an accurate and effective treatment plan.',
    
    'servicesPage.surgery.title': 'Surgical Procedures',
    'servicesPage.surgery.description': 'At Dr. Paws, our highly experienced doctors perform a wide range of surgical procedures using the latest techniques and advanced equipment. We understand that pet surgery can be a stressful time for both pets and their owners, and we are committed to providing a safe, comfortable, and supportive environment throughout the process. Our veterinary surgical clinic services include:',
    'servicesPage.surgery.sterilizationTitle': 'Sterilization Procedures (Spay/Neuter):',
    'servicesPage.surgery.sterilization': 'These routine procedures, spaying for females and neutering for males, help prevent unwanted pregnancies and offer numerous health benefits, including reducing the risk of certain types of cancer and behavioral problems.',
    'servicesPage.surgery.orthopedicTitle': 'Pet Orthopedic Surgery:',
    'servicesPage.surgery.orthopedic': 'The Animal Orthopedic Surgery Clinic treats a variety of bone and joint conditions, including fractures, ligament tears (such as cruciate ligament tears), hip and elbow dysplasia, and other bone problems. Our veterinary orthopedic surgery services aim to restore mobility and improve your pet\'s quality of life.',
    'servicesPage.surgery.digestiveTitle': 'Digestive System Operations:',
    'servicesPage.surgery.digestive': 'Our surgeons are experienced in treating conditions affecting the stomach, intestines, liver, pancreas, and other digestive organs. These procedures may include removal of foreign objects, biopsies, and treatment of conditions such as bloat (gastric dilatation and volvulus).',
    'servicesPage.surgery.rhinoplastyTitle': 'Rhinoplasty (for Brachycephalic Breeds):',
    'servicesPage.surgery.rhinoplasty': 'This procedure is designed specifically for brachycephalic breeds such as Bulldogs, Pugs, and Boxers, where it widens congenitally narrow nostrils to significantly improve breathing and alleviate brachycephalic airway obstruction syndrome.',
    'servicesPage.surgery.urinaryTitle': 'Urinary Tract Surgery:',
    'servicesPage.surgery.urinary': 'We treat a range of urinary tract conditions, including bladder stones, urinary tract obstructions, and other urinary system problems. These procedures aim to restore normal urinary tract function and relieve discomfort.',
    'servicesPage.surgery.closing': 'Before any pet surgical procedure, we conduct a comprehensive pre-surgical evaluation, including a physical examination, blood tests, and other necessary tests, to ensure your pet is a good candidate for surgery. We discuss the procedure, potential risks, and post-operative care instructions with you in detail. We prioritize pain management throughout the surgical process and provide comprehensive post-operative care to ensure a smooth and comfortable recovery. Our veterinary surgical clinic services are a vital part of our commitment to providing complete and compassionate care for your pet.',
    
    'servicesPage.dental.title': 'Dental Services',
    'servicesPage.dental.description': 'Good oral health is crucial to your pet\'s overall health and well-being. Dr. Paws provides comprehensive veterinary dental services designed to maintain your pet\'s teeth and gum health throughout their life. Our services include:',
    'servicesPage.dental.cleaningTitle': 'Professional Teeth Cleaning (Prophylaxis):',
    'servicesPage.dental.cleaning': 'This is the cornerstone of preventive dental care. During professional cleaning, we remove plaque and tartar buildup from above and below the gum line using specialized tools. This process helps prevent periodontal disease, a serious condition that can lead to tooth loss, pain, and even organ damage. We also polish the teeth to create a smooth surface less prone to plaque buildup.',
    'servicesPage.dental.examinationsTitle': 'Comprehensive Dental Examinations (Oral Exams):',
    'servicesPage.dental.examinations': 'Regular dental examinations are essential for early detection of dental problems. During these examinations, our doctors thoroughly assess your pet\'s oral health, checking for signs of periodontal disease, tooth decay, oral tumors, and other abnormalities. We may also recommend dental x-rays to assess the health of tooth roots and surrounding bone structures.',
    'servicesPage.dental.scalingTitle': 'Scaling and Root Planing:',
    'servicesPage.dental.scaling': 'Scaling removes tartar buildup from the tooth surface, above and below the gum line. Root planing smooths the surfaces of tooth roots, making it more difficult for plaque to adhere. This procedure is particularly important for treating periodontal disease and preventing further damage to the gums and supporting bones.',
    'servicesPage.dental.extractionTitle': 'Tooth Extractions:',
    'servicesPage.dental.extraction': 'In cases of severe dental disease, such as advanced periodontal disease or fractured teeth, extraction may be necessary. Our doctors perform extractions with careful attention to pain management and patient comfort.',
    'servicesPage.dental.surgeryTitle': 'Oral Surgery:',
    'servicesPage.dental.surgery': 'For more complex dental problems, such as oral tumors or jaw fractures, we provide advanced oral surgery procedures.',
    'servicesPage.dental.closing': 'Regular dental care, including professional cleaning and home care, is essential to prevent periodontal disease, which can lead to serious health problems affecting the heart, kidneys, and other organs. Our veterinary dental services are designed to maintain your pet\'s oral health, improve their quality of life, and contribute to their overall well-being.',
    
    'servicesPage.vaccination.title': 'Periodic Vaccinations',
    'servicesPage.vaccination.description': 'Pet vaccinations are a cornerstone of preventive veterinary services, protecting your pet from a range of infectious diseases that can potentially threaten their life. At the Dr. Paws Pet Vaccination Clinic, we understand that each pet is unique, so we customize our vaccination protocols based on your pet\'s species, age, lifestyle, and individual risk factors.',
    'servicesPage.vaccination.catTripleTitle': 'Cat Trivalent and Quadrivalent Vaccines',
    'servicesPage.vaccination.catTripleDesc': 'Trivalent and quadrivalent vaccines are among the most important vaccines a cat should receive to protect it from a range of serious viral diseases. The trivalent vaccine consists of protection against three diseases:',
    'servicesPage.vaccination.catTriple': 'Herpes Disease: Causes inflammation of the upper respiratory system in cats and can lead to serious health problems. • Calicivirus Disease: Also causes inflammation of the upper respiratory system and may cause chronic respiratory problems. • Panleukopenia: Also known as feline distemper, it is a highly contagious viral disease that affects the digestive system and causes diarrhea, vomiting, and dehydration, and can be fatal.',
    'servicesPage.vaccination.catQuad': 'The quadrivalent vaccine, in addition to the trivalent vaccine, provides protection against feline leukemia, which is a cancerous disease that affects the immune system of cats.',
    'servicesPage.vaccination.catBenefitsTitle': 'Benefits of Trivalent and Quadrivalent Vaccines:',
    'servicesPage.vaccination.catBenefits': 'Protection from Fatal Diseases: These vaccines protect cats from diseases that can be fatal or cause serious health complications. • Strengthening the Immune System: These vaccines help strengthen the immune system of cats, making them more resistant to diseases. • Prevention of Disease Spread: These vaccines help prevent the spread of diseases among other cats.',
    'servicesPage.vaccination.dogPentaTitle': 'Dog Pentavalent Vaccine',
    'servicesPage.vaccination.dogPentaDesc': 'The pentavalent vaccine is one of the most important vaccines that a dog should receive to protect it from a range of serious viral and bacterial diseases. The pentavalent vaccine consists of protection against five diseases:',
    'servicesPage.vaccination.dogPenta': 'Rabies: A serious viral disease that affects the nervous system and leads to death. • Parvovirus: A highly contagious viral disease that affects the digestive system and causes diarrhea, vomiting, and dehydration, and can be fatal. • Adenovirus: Causes inflammation of the respiratory and digestive systems. • Parainfluenza: Causes inflammation of the digestive system. • Bordetella: Causes inflammation of the respiratory system.',
    'servicesPage.vaccination.dogBenefitsTitle': 'Benefits of the Pentavalent Vaccine:',
    'servicesPage.vaccination.dogBenefits': 'Protection from Fatal Diseases: This vaccine protects dogs from diseases that can be fatal or cause serious health complications. • Strengthening the Immune System: This vaccine helps strengthen the immune system of dogs, making them more resistant to diseases. • Prevention of Disease Spread: This vaccine helps prevent the spread of diseases among other dogs.',
    'servicesPage.vaccination.rabiesTitle': 'Rabies Vaccine',
    'servicesPage.vaccination.rabies': 'The rabies vaccine is one of the most important vaccines that both dogs and cats should receive, as this vaccine protects against rabies, which is a viral disease that affects the nervous system and leads to death. Rabies can be transmitted to humans through the bite of an infected animal, so vaccinating pets is an important means of preventing the spread of this disease.',
    'servicesPage.vaccination.dewormTitle': 'Deworming',
    'servicesPage.vaccination.deworm': 'Deworming is not exactly a vaccination, but rather medications used to eliminate intestinal worms that may infect pets. These medications should be given periodically according to the veterinarian\'s instructions, especially for animals that go outdoors or that come into contact with other animals.',
    
    'servicesPage.travel.title': 'Pet Travel Procedures',
    'servicesPage.travel.description': 'Traveling with your pet can be a rewarding experience, but it requires careful planning and adherence to specific regulations. Dr. Paws provides comprehensive pet travel procedure services to ensure smooth and safe travel for pets, whether domestically or internationally. We understand that each destination has unique requirements, and our experienced team is here to guide you.',
    'servicesPage.travel.certificatesTitle': 'Health Certificates:',
    'servicesPage.travel.certificates': 'A health certificate is an official document issued by a licensed veterinarian, certifying that your pet is in good health and free from infectious diseases. This certificate is often required for travel across state lines or internationally. We will conduct a thorough physical examination of your pet to ensure they meet the necessary health standards. The specific requirements for health certificates vary by destination, so it is essential to contact us well in advance of your travel date.',
    'servicesPage.travel.rabiesTitle': 'Rabies Testing for Travel Purposes:',
    'servicesPage.travel.rabies': 'Rabies is a serious viral disease, and many countries require proof of rabies vaccination and/or a rabies titer test for entry. The rabies titer test measures the level of rabies antibodies in your pet\'s blood, confirming adequate immunity. Our veterinary services include administering rabies vaccinations (if needed) and performing rabies titer tests. We will provide you with the official documentation required for international travel, ensuring they meet the specific requirements of your destination country. Please note that there are often waiting periods after vaccination or testing before travel is permitted.',
    'servicesPage.travel.formsTitle': 'Certificate Form Completion:',
    'servicesPage.travel.forms': 'The paperwork required for international pet travel can be complex and confusing, as different countries have different forms and requirements. Our experienced team can help you accurately and efficiently complete the necessary certificate forms. We stay updated on the latest regulations for various destinations, including European countries and those requiring specific certified certificates from APHIS USDA (United States Department of Agriculture, Animal and Plant Health Inspection Service). We will ensure all forms are properly completed and certified, minimizing the risk of delays or complications during your travel.',
    'servicesPage.travel.closing': 'These veterinary services for pet travel procedures are designed to make the process as stress-free as possible for you and your pet. We recommend contacting us weeks or even months before your planned travel date to allow sufficient time for necessary examinations, tests, and paperwork.',
    
    'servicesPage.boarding.title': 'Boarding Services',
    'servicesPage.boarding.description': 'At Dr. Paws, we understand that leaving your pet can be stressful. That is why we provide comfortable boarding and animal hotel care as part of our comprehensive veterinary services. We cater to a diverse range of needs with specialized boarding options:',
    'servicesPage.boarding.therapeuticTitle': 'Therapeutic Pet Hotel:',
    'servicesPage.boarding.therapeuticDesc': 'Our therapeutic pet hotel is designed for pets that require specialized medical care during their stay. This option is ideal for:',
    'servicesPage.boarding.therapeutic': 'Post-Surgery Recovery: Pets recovering from surgical procedures receive close monitoring, pain management, and mobility assistance as needed. Our trained team ensures their comfort and proper healing. • Chronic Condition Management: Pets suffering from conditions such as diabetes, kidney disease, or heart disease receive individualized care, including medication administration, specialized diets, and regular monitoring of their condition. • Pets Requiring Close Monitoring: Pets suffering from unstable medical conditions or those requiring frequent observation benefit from the close attention of our veterinary team. We monitor vital signs, administer medications, and provide any necessary treatments.',
    
    'servicesPage.intensiveCare.title': 'Intensive Care',
    'servicesPage.intensiveCare.description': 'The intensive care unit at Dr. Paws provides specialized 24/7 care for pets suffering from critical conditions or serious illnesses. Equipped with the latest monitoring devices and highly trained veterinary staff, we provide a safe, closely monitored environment to support your pet\'s recovery. We treat a wide range of critical conditions, including:',
    'servicesPage.intensiveCare.organ': 'Organ Failure Management: Specialized care for pets suffering from kidney, liver, or heart failure.',
    'servicesPage.intensiveCare.metabolic': 'Metabolic and Endocrine Disorders: Management of conditions such as diabetes, Addison\'s disease, and thyroid crises.',
    'servicesPage.intensiveCare.trauma': 'Severe Injuries and Trauma: Immediate, intensive care for pets that have been in accidents or suffered serious injuries.',
    'servicesPage.intensiveCare.postSurgical': 'Post-Surgical Care: Close monitoring for pets that have undergone complex surgeries.',
    
    'servicesPage.emergency.title': 'Emergency Services',
    'servicesPage.emergency.description': 'We recognize that emergencies can happen at any time, which is why Dr. Paws provides comprehensive 24/7 veterinary emergency services. Our trained team is prepared to provide immediate and critical care for your pet in times of urgent need. We treat a wide range of emergency conditions, including:',
    'servicesPage.emergency.trauma': 'Trauma: Car accidents, falls, wounds, and other injuries.',
    'servicesPage.emergency.breathing': 'Breathing Difficulties: Shortness of breath, choking, or any other respiratory distress.',
    'servicesPage.emergency.bleeding': 'Bleeding or Poisoning: Severe blood loss or accidental ingestion of toxic substances.',
    'servicesPage.emergency.seizures': 'Seizures and Bloat: Unexpected seizures or life-threatening stomach bloat conditions.',
    'servicesPage.emergency.numbers': 'Emergency Numbers:',
    'servicesPage.emergency.sahafa': 'Al-Sahafa Branch: 0552030564',
    'servicesPage.emergency.mather': 'Al-Mather Branch: 0531353667',
    
    'servicesPage.homeCare.title': 'Home Care Services',
    'servicesPage.homeCare.description': 'We recognize that some pets may feel stressed when visiting the clinic, or that some pet owners may face transportation difficulties. Therefore, Dr. Paws provides convenient home veterinary care services, where we come to you! This service allows your pet to receive high-quality veterinary care in the comfort of their familiar home, reducing stress and providing a more relaxing experience. Our home veterinary care services include:',
    'servicesPage.homeCare.wellness': 'Wellness Exams: Conducting comprehensive physical examinations to assess your pet\'s overall health.',
    'servicesPage.homeCare.vaccinations': 'Vaccinations: Administering essential vaccinations to keep your pet protected from infectious diseases.',
    'servicesPage.homeCare.sample': 'Sample Collection (blood, urine, fecal): Collecting necessary samples for laboratory tests without needing to visit the clinic.',
    
    // Footer
    'footer.description': 'From wellness exams to advanced treatments, Dr. Paws provides comprehensive veterinary care for your pet\'s every need.',
    'footer.contactInfo': 'Contact Information',
    'footer.call': 'Call',
    'footer.generalPhone': '920 003 045',
    'footer.emergency': 'Emergency: 24/7',
    'footer.mobile': 'Mobile',
    'footer.sahafahBranch': 'Al-Sahafa Branch',
    'footer.sahafahAddress': 'Dr.Paws Veterinary Clinic, Al Thoumamah Rd, As Sahafah, Riyadh 13315',
    'footer.sahafahPhone': '05520 30564',
    'footer.sahafahMapUrl': 'https://www.google.com/maps/search/?api=1&query=Dr.Paws+Veterinary+Clinic,Al+Thoumamah+Rd,As+Sahafah,Riyadh+13315',
    'footer.matherBranch': 'Al-Mather Branch',
    'footer.matherAddress': 'Dr.Paws Veterinary Clinic, Prince Sultan Bin Abdulaziz Rd, Al Mathar Ash Shamali, Riyadh 12314',
    'footer.matherPhone': '0531353667',
    'footer.matherMapUrl': 'https://www.google.com/maps/search/?api=1&query=Dr.Paws+Veterinary+Clinic,Prince+Sultan+Bin+Abdulaziz+Rd,Al+Mathar+Ash+Shamali,Riyadh+12314',
    'footer.hours': 'Working Hours',
    'footer.satThu': 'Sat – Thu: 09:00 AM – 10:00 PM',
    'footer.fri': 'Fri: 03:00 PM – 10:00 PM',
    'footer.email': 'info@drpaws-sa.com',
    'footer.follow': 'Stay in touch',
  },
  ar: {
    // Navigation
    'nav.home': 'الرئيسية',
    'nav.about': 'من نحن',
    'nav.services': 'الخدمات',
    'nav.blog': 'المدونة',
    'nav.contact': 'تواصل معنا',
    'nav.book': 'احجز موعد',
    
    // Hero
    'hero.headline': 'عيادات د. باوز البيطرية',
    'hero.tagline': 'رعاية من القلب لحيواناتكم الأليفة',
    'hero.subheadline': 'عيادة بيطرية متخصصة تمنحهم أفضل رعاية ممكنة',
    'hero.description': 'عيادة د. باوز تُقدّم أحدث ما توصلت إليه التكنولوجيا في مجال الرعاية البيطرية. من خلال فريقنا الخبير وباستخدام أحدث الأجهزة والتقنيات التشخيصية والعلاجية، نضمن تقديم رعاية شاملة ومتطورة تشمل جميع الخدمات من الفحوصات الروتينية إلى الجراحات الدقيقة.',
    'hero.cta': 'احجز موعدك الآن',
    'hero.readMore': 'اقرأ المزيد',
    
    // About
    'about.headline': 'عيادات د. باوز البيطرية: رعاية متكاملة لصحة حيوانك الأليف',
    'about.description': 'في عيادات د. باوز البيطرية، نتفهم الرابطة الخاصة التي تجمعك بحيوانك الأليف. فريقنا ذو الخبرة والرحمة ملتزم بتقديم رعاية بيطرية شاملة وعالية الجودة للحفاظ على صحة وسعادة رفاقك طوال حياتهم. نسعى لخلق بيئة مريحة وترحيبية لك ولحيوانك الأليف.',
    'about.readMore': 'اقرأ المزيد',
    
    // Services
    'services.headline': 'ماذا نقدم؟',
    'services.description': 'تقدم عيادات د. باوز البيطرية باقة متكاملة من الخدمات البيطرية الشاملة لتلبية احتياجات حيوانك الأليف في جميع مراحل حياته. من الفحوصات الوقائية إلى التشخيصات المتقدمة والجراحات المتخصصة. نحن هنا لضمان صحة أليفك.',
    'services.readMore': 'اقرأ المزيد',
    'services.wellness.title': 'الفحوصات الصحية',
    'services.wellness.description': 'فحوصات صحية شاملة للحفاظ على حيوانك الأليف في حالة مثالية.',
    'services.emergency.title': 'الرعاية الطارئة',
    'services.emergency.description': 'خدمات طوارئ على مدار الساعة للحالات الطبية العاجلة.',
    'services.vaccinations.title': 'التطعيمات',
    'services.vaccinations.description': 'برامج تطعيم كاملة لحماية حيواناتك من الأمراض.',
    'services.surgery.title': 'الجراحة',
    'services.surgery.description': 'إجراءات جراحية متقدمة بأحدث المعدات.',
    'services.diagnostics.title': 'التشخيص',
    'services.diagnostics.description': 'تصوير تشخيصي متقدم وخدمات مخبرية.',
    'services.dental.title': 'العناية بالأسنان',
    'services.dental.description': 'تنظيف أسنان احترافي وخدمات صحة الفم.',
    
    // Service Packages
    'packages.headline': 'باقات الخدمات',
    'packages.description': 'اختر باقة الرعاية المثالية التي تناسب احتياجات حيوانك الأليف. جميع الباقات تشمل رعاية بيطرية شاملة مصممة للحفاظ على صحة وسعادة رفيقك المحبوب.',
    'packages.basic.name': 'الرعاية الأساسية',
    'packages.basic.price': '٢٩٩',
    'packages.basic.period': 'ريال/سنة',
    'packages.basic.feature1': 'فحص صحي سنوي',
    'packages.basic.feature2': 'تطعيمات أساسية',
    'packages.basic.feature3': 'الوقاية من الطفيليات',
    'packages.basic.feature4': 'استشارة الأسنان',
    'packages.basic.feature5': 'إرشادات التغذية',
    'packages.complete.name': 'الرعاية الكاملة',
    'packages.complete.price': '٥٩٩',
    'packages.complete.period': 'ريال/سنة',
    'packages.complete.feature1': 'فحوصات صحية نصف سنوية',
    'packages.complete.feature2': 'باقة تطعيمات كاملة',
    'packages.complete.feature3': 'وقاية متقدمة من الطفيليات',
    'packages.complete.feature4': 'تنظيف الأسنان متضمن',
    'packages.complete.feature5': 'فحوصات الدم والتشخيص',
    'packages.complete.feature6': 'خصم على الرعاية الطارئة',
    'packages.premium.name': 'الرعاية المميزة',
    'packages.premium.price': '٩٩٩',
    'packages.premium.period': 'ريال/سنة',
    'packages.premium.feature1': 'فحوصات صحية ربع سنوية',
    'packages.premium.feature2': 'باقة تطعيمات مميزة',
    'packages.premium.feature3': 'وقاية على مدار العام',
    'packages.premium.feature4': 'رعاية أسنان احترافية',
    'packages.premium.feature5': 'فحوصات مخبرية شاملة',
    'packages.premium.feature6': 'رعاية طارئة ذات أولوية',
    'packages.premium.feature7': 'استشارة بيطرية ٢٤/٧',
    'packages.popular': 'الأكثر شعبية',
    'packages.bookNow': 'احجز الآن',
    
    // Media
    'media.headline': 'الوسائط',
    'media.description': 'ألقِ نظرة فاحصة على مرافقنا الحديثة وشاهد كيف نقدم رعاية استثنائية لحيواناتك الأليفة في بيئة دافئة ومرحبة.',
    
    // Why Choose Us
    'why.headline': 'لماذا تختار عيادات د. باوز البيطرية؟',
    'why.reason1.title': 'رعاية شاملة وحنونة',
    'why.reason1.description': 'نعامل كل حيوان أليف كما لو كان ملكنا، بلطف واحترام وتفهّم.',
    'why.reason2.title': 'فريق ذو خبرة',
    'why.reason2.description': 'أطباؤنا وطاقمنا لديهم سنوات من الخبرة وشغف بصحة الحيوانات الأليفة.',
    'why.reason3.title': 'عيادات متطورة وحديثة',
    'why.reason3.description': 'نستخدم أحدث المعدات والتقنيات لتوفير أفضل رعاية ممكنة.',
    'why.reason4.title': 'خطة علاجية مخصصة',
    'why.reason4.description': 'نضع خطة علاج تناسب الاحتياجات الفريدة لكل حيوان أليف.',
    'why.readMore': 'اقرأ المزيد',
    
    // Reviews
    'reviews.headline': 'آراء عملائنا',
    'reviews.1.name': 'أحمد الرشيد',
    'reviews.1.text': 'خدمة ممتازة! الطاقم كان رائعًا ومهنيًا جدًا مع قطتي. أنصح بشدة بعيادة د. باوز!',
    'reviews.2.name': 'سارة جونسون',
    'reviews.2.text': 'كلبي حصل على أفضل رعاية هنا. الأطباء ذوو خبرة والعيادة نظيفة جدًا.',
    'reviews.3.name': 'محمد حسن',
    'reviews.3.text': 'تجربة رائعة بشكل عام. الطبيب البيطري شرح كل شيء بوضوح وحيواني الأليف يشعر بتحسن كبير.',
    'reviews.4.name': 'إميلي رودريجيز',
    'reviews.4.text': 'خدمة الطوارئ كانت مميزة. اهتموا بأرنبي فورًا وبشكل احترافي.',
    'reviews.5.name': 'خالد عبدالله',
    'reviews.5.text': 'أفضل عيادة بيطرية في الرياض! الطاقم ودود ويهتمون حقًا بالحيوانات.',
    'reviews.6.name': 'جينيفر لي',
    'reviews.6.text': 'معجبة جدًا بالمرافق ومستوى الرعاية. ببغائي حصل على علاج ممتاز.',
    'reviews.7.name': 'عمر سعيد',
    'reviews.7.text': 'فريق محترف ومعدات حديثة. جعلوا حيواني الأليف يشعر بالراحة خلال الزيارة.',
    'reviews.8.name': 'ليزا مارتينيز',
    'reviews.8.text': 'تجربة رائعة! خدمة التجميل كانت مثالية وكلبي يبدو رائعًا. شكرًا لكم!',
    
    // Contact
    'contact.headline': 'تواصل معنا',
    'contact.subheadline': 'بادر بحجز موعد لحيوانك الأليف في عيادة د. باوز البيطرية اليوم!',
    'contact.name': 'الاسم',
    'contact.phone': 'رقم الهاتف',
    'contact.email': 'البريد الإلكتروني',
    'contact.message': 'الرسالة',
    'contact.submit': 'إرسال',
    'contact.success': 'شكراً لك! سنتواصل معك قريباً.',
    
    // About Page
    'aboutPage.header': 'عيادات د. باوز البيطرية بالرياض',
    'aboutPage.subheader': 'خبرة نضعها بين أيديكم بكل ثقة',
    'aboutPage.whoWeAre.title': 'من نحن؟',
    'aboutPage.whoWeAre.subtitle': '',
    'aboutPage.whoWeAre.para1': 'تُقدّم عيادات د. باوز، أفضل عيادة بيطرية بالرياض، رعاية بيطرية استثنائية تجمع بين الخبرة والتقنية الحديثة، مع لمسة حانية تُعبّر عن اهتمامنا العميق بصحة حيواناتكم الأليفة. من الفحوصات الروتينية إلى التشخيصات المتقدمة والعلاجات المتخصصة، نُوفّر رعاية شاملة في بيئة مريحة وودية، لضمان تجربة إيجابية لكم ولحيواناتكم الأليفة في كل زيارة.',
    'aboutPage.whoWeAre.para2': '',
    'aboutPage.whoWeAre.para3': '',
    'aboutPage.vision.title': 'رؤيتنا',
    'aboutPage.vision.content': 'تسعى عيادات دكتور باوز إلى أن تكون المرجع الأول والأفضل في مجال الرعاية البيطرية، حيث تقدم أعلى مستوى من الرعاية الصحية للحيوانات الأليفة.',
    'aboutPage.mission.title': 'مهمتنا',
    'aboutPage.mission.content': 'توفير رعاية بيطرية شاملة وعالية الجودة للحيوانات الأليفة، مع التركيز على صحة ورفاهية الحيوان، وتقديم أفضل الخدمات الطبية للحيوانات الأليفة، بدءًا من الفحوصات الروتينية وحتى الجراحات المعقدة، وذلك من خلال فريق عمل متخصص وبيئة مريحة لأليفك.',
    'aboutPage.whyChoose.title': 'لماذا تختار عيادات د. باوز البيطرية؟',
    'aboutPage.whyChoose.reason1.title': 'رعاية شاملة وحنونة',
    'aboutPage.whyChoose.reason1.description': 'نعامل كل حيوان أليف كما لو كان حيواننا الأليف، باللطف والاحترام والتفهّم.',
    'aboutPage.whyChoose.reason2.title': 'فريق ذو خبرة',
    'aboutPage.whyChoose.reason2.description': 'يتمتع أطباؤنا البيطريون وطاقم الدعم لدينا بخبرة سنوات عديدة وشغف تجاه الحيوانات الأليفة.',
    'aboutPage.whyChoose.reason3.title': 'عيادات متطورة وحديثة',
    'aboutPage.whyChoose.reason3.description': 'حيث نستخدم أحدث التقنيات والمعدات لتوفير أفضل رعاية ممكنة.',
    'aboutPage.whyChoose.reason4.title': 'خطة علاجية تناسب أليفك',
    'aboutPage.whyChoose.reason4.description': 'نُعدل خطط العلاج لتلبية الاحتياجات الفريدة لكل حيوان أليف.',
    'aboutPage.doctors.title': 'فريق العمل',
    'aboutPage.doctors.description': 'في عيادات د. باوز، أفضل عيادة بيطرية بالرياض، يجمع فريقنا من الأطباء البيطريين بين الخبرة العالية والتعاطف العميق لتقديم رعاية شاملة ومتخصصة. ملتزمون بتطبيق أعلى معايير الجودة في كل جوانب الرعاية، وشغفهم بصحة الحيوانات هو الدافع الأساسي لعملهم. خبراتهم المتنوعة تُمكّنهم من توفير أفضل الحلول العلاجية لحيوانكم الأليف.',
    'aboutPage.doctors.noInfo': 'ملفات تعريف الأطباء قريباً',
    'aboutPage.partners.title': 'شركاؤنا',
    'aboutPage.partners.noInfo': 'معلومات الشركاء قريباً',
    'aboutPage.careers.title': 'الوظائف',
    'aboutPage.careers.description': 'عيادة د. باوز، أفضل عيادة بيطرية بالرياض، تدعوك للانضمام إلى فريقها المتميز. نوفر لك بيئة عمل داعمة ومُحفّزة تُساعدك على التطور المهني واكتساب الخبرات القيمة في مجال صحة الحيوان.',
    'aboutPage.careers.personalInfo': 'المعلومات الشخصية',
    'aboutPage.careers.fullName': 'الاسم الكامل',
    'aboutPage.careers.email': 'البريد الإلكتروني',
    'aboutPage.careers.phone': 'رقم الهاتف',
    'aboutPage.careers.professionalInfo': 'المعلومات المهنية',
    'aboutPage.careers.resume': 'تحميل السيرة الذاتية',
    'aboutPage.careers.coverLetter': 'الخطاب التعريفي (اختياري)',
    'aboutPage.careers.position': 'الوظيفة المطلوبة (إن وجدت)',
    'aboutPage.careers.startDate': 'تاريخ البدء المتاح',
    'aboutPage.careers.experience': 'الخبرة ذات الصلة',
    'aboutPage.careers.experiencePlaceholder': 'مثلاً: فني بيطري، مساعد بيطري، موظف استقبال',
    'aboutPage.careers.certifications': 'الشهادات البيطرية (إن وجدت)',
    'aboutPage.careers.education': 'المستوى التعليمي والمؤسسة',
    'aboutPage.careers.interests': 'مجالات الاهتمام',
    'aboutPage.careers.interestsPlaceholder': 'مثلاً: الجراحة، الطب الباطني، رعاية الطوارئ',
    'aboutPage.careers.submit': 'إرسال الطلب',
    
    // Services Page
    'servicesPage.header': 'خدماتنا',
    'servicesPage.subheader': 'اختبر أفضل رعاية بيطرية في أفضل عيادة حيوانات أليفة: د. باوز. نقدم نطاقًا كاملاً من الرعاية لحيواناتكم الأليفة، من الفحوصات الروتينية إلى العلاجات المتقدمة.',
    'servicesPage.mainHeadline': 'استمتع بتجربة رعاية بيطرية شاملة ومُتميزة في د. باوز، أفضل عيادة حيوانات أليفة',
    'servicesPage.bookAppointment': 'احجز موعدك اليوم!',
    
    // Examinations
    'servicesPage.examinations.title': 'الفحص الطبي الدوري',
    'servicesPage.examinations.description': 'في د. باوز، نؤمن بأن الرعاية الوقائية أساسية لحياة صحية مديدة لجميع الحيوانات الأليفة. فحوصاتنا الدورية، المعروفة أيضًا باسم فحوصات الصحة العامة أو الفحوصات الروتينية، تُعدّ جزءًا حيويًا من خدماتنا البيطرية الشاملة. تُتيح هذه الزيارات الروتينية لأطبائنا تقييم صحة حيوانك الأليف بشكل عام، واكتشاف المشاكل المحتملة في وقت مبكر، وتقديم توصيات مُخصّصة لرعايتهم المُستمرة.',
    'servicesPage.examinations.canineTitle': 'الفحوصات الدورية للكلاب:',
    'servicesPage.examinations.canineIntro': 'خلال الفحص الطبي الدوري للكلاب، نُجري فحصًا بدنيًا شاملاً، يشمل:',
    'servicesPage.examinations.canine': 'العلامات الحيوية: فحص درجة الحرارة والنبض ومعدل التنفس. • سماع القلب والرئتين: الاستماع إلى القلب والرئتين للكشف عن أي تشوهات. • فحص العيون: فحص العيون للكشف عن علامات إعتام عدسة العين أو الجلوكوما أو غيرها من أمراض العيون. • فحص الأذنين: فحص الأذنين للكشف عن الالتهابات أو العث أو مشاكل الأذن الأخرى. • فحص الفم: تقييم الأسنان واللثة للكشف عن تراكم الجير أو التهاب اللثة ومشاكل الأسنان الأخرى. • فحص الجلد: فحص الجلد والفراء للكشف عن الحساسية أو الالتهابات أو الطفيليات أو مشاكل الجلد الأخرى. • جس البطن: جس البطن بلطف للتحقق من تضخم الأعضاء أو الكتل أو غيرها من التشوهات. • تقييم الجهاز العضلي الهيكلي: تقييم المفاصل والعضلات للكشف عن علامات التهاب المفاصل أو العرج أو مشاكل الجهاز العضلي الهيكلي الأخرى.',
    'servicesPage.examinations.felineTitle': 'الفحوصات الدورية للقطط:',
    'servicesPage.examinations.felineIntro': 'تُجرى الفحوصات الطبية الدورية للقطط بنهج لطيف وصبور، لتقليل التوتر على قطتك. يشمل الفحص:',
    'servicesPage.examinations.feline': 'العلامات الحيوية: فحص درجة الحرارة والنبض ومعدل التنفس. • سماع القلب والرئتين: الاستماع إلى القلب والرئتين للكشف عن أي تشوهات. • فحص العيون: فحص العيون للكشف عن علامات إعتام عدسة العين أو الجلوكوما أو غيرها من أمراض العيون. • فحص الأذنين: فحص الأذنين للكشف عن الالتهابات أو العث أو مشاكل الأذن الأخرى. • فحص الفم: تقييم الأسنان واللثة للكشف عن تراكم الجير أو التهاب اللثة ومشاكل الأسنان الأخرى. • فحص الجلد: فحص الجلد والفراء للكشف عن الحساسية أو الالتهابات أو الطفيليات أو مشاكل الجلد الأخرى. • جس البطن: جس البطن بلطف للتحقق من تضخم الأعضاء أو الكتل أو غيرها من التشوهات.',
    'servicesPage.examinations.avianTitle': 'الفحوصات الدورية للطيور:',
    'servicesPage.examinations.avianIntro': 'تتطلب الفحوصات الطبية الدورية للطيور معرفة متخصصة وتقنيات تعامل خاصة. تشمل فحوصات الطيور لدينا:',
    'servicesPage.examinations.avian': 'الفحص البدني: تقييم دقيق للريش والمنقار والعينين والمنخر (فتحات الأنف) والاستماع إلى القلب والرئتين. • تسجيل الوزن وحالة الجسم: تقييم الصحة العامة والحالة التغذوية. • فحص الغدة الذيلية: فحص غدة الزيت للكشف عن أي تشوهات. • جس البطن: جس لطيف للتحقق من تضخم الأعضاء أو مشاكل أخرى.',
    'servicesPage.examinations.closing': 'الفحوصات المنتظمة ضرورية للحفاظ على صحة حيوانك الأليف ومنع المشاكل الصحية الخطيرة. نوصي بتكرار هذه الفحوصات بناءً على نوع حيوانك وعمره وسلالته وتاريخه الصحي. اتصل بنا لتحديد موعد زيارة صحية لحيوانك الأليف والتأكد من حصوله على خدمات بيطرية شاملة في أفضل عيادة حيوانات أليفة.',
    
    // Grooming
    'servicesPage.grooming.title': 'خدمات العناية بالنظافة والمظهر',
    'servicesPage.grooming.description': 'يُساهم الحفاظ على نظافة ومظهر حيوانك الأليف بشكل كبير في صحته العامة وراحته ورفاهيته. في د. باوز، نُقدّم مجموعة من خدمات عيادة رعاية نظافة الحيوانات الفعّالة والمُصمّمة للحفاظ على مظهر حيوانك الأليف بأفضل حال. هذه الخدمات، على الرغم من أنها ليست طبية بحتة، إلا أنها جزء مهم من الرعاية الوقائية وتُكمّل خدماتنا البيطرية الأخرى:',
    'servicesPage.grooming.nailTrimmingTitle': 'تقليم الأظافر:',
    'servicesPage.grooming.nailTrimming': 'يُعدّ تقليم الأظافر المنتظم ضروريًا لمنع النمو الزائد، الذي يُمكن أن يُسبب انزعاجًا مؤلمًا وصعوبة في المشي وحتى مشاكل في المفاصل. نُقدّم خدمة تقليم الأظافر للكلاب والقطط والطيور، باستخدام تقنيات تُقلّل التوتر وتضمن تجربة مُريحة.',
    'servicesPage.grooming.earCleaningTitle': 'تنظيف الأذنين:',
    'servicesPage.grooming.earCleaning': 'آذان نظيفة هي آذان صحية! تُساعد خدمة تنظيف الأذنين لدينا في منع الالتهابات وإزالة تراكم الشمع والحفاظ على راحة حيوانك الأليف. هذه الخدمة مُتاحة للكلاب والقطط وهي مُفيدة بشكل خاص للسلالات المُعرّضة لمشاكل الأذن.',
    'servicesPage.grooming.bathingTitle': 'الاستحمام والتجفيف:',
    'servicesPage.grooming.bathing': 'نُقدّم خدمات استحمام وتجفيف مُهدّئة باستخدام شامبو وبلسم عالي الجودة وآمن للحيوانات الأليفة. تُساعد هذه الخدمة في إزالة الأوساخ والحطام والروائح، مما يترك فراء حيوانك الأليف نظيفًا وناعمًا وصحيًا. هذه الخدمة مُخصّصة بشكل أساسي للكلاب والقطط ويُمكن تعديلها لتناسب نوع بشرتهم.',
    'servicesPage.grooming.groomingTitle': 'تمشيط وقص الشعر (التزيين):',
    'servicesPage.grooming.grooming': 'يُعدّ التزيين المنتظم، بما في ذلك التمشيط وقص الشعر، ضروريًا للحفاظ على فراء صحي وسهل التصفيف. يُقدّم مُزيّنونا ذوو الخبرة قصات شعر خاصة بالسلالات وخدمات فك التشابك اللطيفة، مما يُساعد في منع التشابك المؤلم وتهيج الجلد. هذه الخدمة مُخصّصة بشكل أساسي للكلاب والقطط ذات الفراء الطويل أو الكثيف.',
    
    // Diagnostics
    'servicesPage.diagnostics.title': 'الاختبارات التشخيصية',
    'servicesPage.diagnostics.description': 'يُعدّ التشخيص الدقيق وفي الوقت المناسب أمرًا بالغ الأهمية للعلاج الفعّال. في مركز تحليل الحيوانات في د.باوز، نُقدّم مجموعة شاملة من خدمات التشخيص البيطرية لتقييم صحة حيوانك الأليف بسرعة ودقة. مركز تحليل الحيوانات في د.باوز مُجهز بأحدث تقنيات التشخيص، مما يُتيح لنا إجراء مجموعة مُتنوعة من الاختبارات، بما في ذلك:',
    'servicesPage.diagnostics.labTitle': 'التحاليل:',
    'servicesPage.diagnostics.lab': 'اختبارات الدم الكيميائية: تُقيّم هذه الاختبارات وظائف الأعضاء (الكبد والكلى والبنكرياس) وتوازن الكهارل ومعايير الدم المهمة الأخرى. • صورة الدم الكاملة: يُقدّم معلومات حول خلايا الدم الحمراء والبيضاء والصفائح الدموية ومكونات الدم الأخرى، مما يُساعد في تشخيص الالتهابات وفقر الدم واضطرابات الدم الأخرى. • تحليل البول: يُقيّم هذا الاختبار وظائف الكلى ويكشف عن التهابات المسالك البولية ويُحدّد تشوهات الجهاز البولي الأخرى. • فحوصات الطفيليات المعوية: فحص مجهري لعينات البراز للكشف عن الطفيليات المعوية وتحديدها. • فحوصات الأمراض الفطرية: اختبارات مُتنوعة، بما في ذلك الفحص المجهري والمزارع، لتشخيص الالتهابات الفطرية. • فحوصات الأمراض الفيروسية: استخدام طرق تشخيصية مُتنوعة للكشف عن الالتهابات الفيروسية.',
    'servicesPage.diagnostics.imagingTitle': 'التصوير:',
    'servicesPage.diagnostics.imaging': 'الأشعة السينية (التصوير الشعاعي): توفير صور تفصيلية للعظام والمفاصل والأعضاء الداخلية. • الأشعة السينية للأسنان: تُستخدم خصيصًا لتقييم صحة الأسنان وهياكل العظام المُحيطة بها. • الموجات فوق الصوتية: استخدام الموجات الصوتية لإنشاء صور حية للأعضاء الداخلية، مما يُتيح تقييمًا تفصيليًا لبنيتها ووظيفتها.',
    'servicesPage.diagnostics.advancedTitle': 'التشخيصات المتقدمة:',
    'servicesPage.diagnostics.advanced': 'الفحص المجهري: فحص العينات (مثل الدم أو الأنسجة أو البول) تحت المجهر لتحديد الخلايا أو البكتيريا أو الطفيليات أو غيرها من التشوهات. • التنظير الداخلي والخارجي: استخدام كاميرا صغيرة مُثبّتة بأنبوب مرن لرؤية داخل الأعضاء أو تجاويف الجسم.',
    'servicesPage.diagnostics.closing': 'تُمكّن هذه الخدمات التشخيصية البيطرية الشاملة أطباءنا من تحديد سبب مرض أو إصابة حيوانك الأليف ووضع خطة علاج دقيقة وفعّالة.',
    
    // Surgery
    'servicesPage.surgery.title': 'العمليات الجراحية',
    'servicesPage.surgery.description': 'في د. باوز، يُجري أطباؤنا ذوو الخبرة الواسعة مجموعة واسعة من العمليات الجراحية باستخدام أحدث التقنيات والمعدات المتطورة. نتفهم أن جراحة الحيوانات الأليفة قد تكون وقتًا عصيبًا لكل من الحيوانات الأليفة وأصحابها، ونحن ملتزمون بتوفير بيئة آمنة ومريحة وداعمة طوال العملية. وتشمل خدمات عيادة الجراحة البيطرية:',
    'servicesPage.surgery.sterilizationTitle': 'عمليات التعقيم (الخصي/استئصال المبيض):',
    'servicesPage.surgery.sterilization': 'تُساعد هذه الإجراءات الروتينية، استئصال المبيض للإناث والخصي للذكور، في منع الحمل غير المرغوب فيه وتوفر فوائد صحية عديدة، بما في ذلك تقليل خطر الإصابة بأنواع معينة من السرطان والمشاكل السلوكية.',
    'servicesPage.surgery.orthopedicTitle': 'جراحة العظام للحيوانات الأليفة:',
    'servicesPage.surgery.orthopedic': 'عيادة جراحة العظام للحيوانات تعالج مجموعة متنوعة من حالات العظام والمفاصل، بما في ذلك الكسور وتمزق الأربطة (مثل تمزق الرباط الصليبي) وخلل تنسج الورك والكوع ومشاكل العظام الأخرى. تهدف خدماتنا البيطرية لجراحة العظام إلى استعادة الحركة وتحسين جودة حياة حيوانك الأليف.',
    'servicesPage.surgery.digestiveTitle': 'عمليات الجهاز الهضمي:',
    'servicesPage.surgery.digestive': 'يتمتع جراحونا بخبرة في علاج الحالات التي تُصيب المعدة والأمعاء والكبد والبنكرياس والأعضاء الهضمية الأخرى. قد تشمل هذه الإجراءات إزالة الأجسام الغريبة والخزعات وعلاج حالات مثل الانتفاخ (توسع المعدة والالتواء).',
    'servicesPage.surgery.rhinoplastyTitle': 'تجميل الأنف (للسلالات قصيرة الأنف):',
    'servicesPage.surgery.rhinoplasty': 'صُمّم هذا الإجراء خصيصًا للسلالات قصيرة الأنف مثل كلاب البولدوج والباج والبوكسر، حيث يُوسّع فتحات الأنف الضيقة خلقيًا لتحسين التنفس بشكل كبير وتخفيف متلازمة انسداد مجرى الهواء في الكلاب قصيرة الرأس.',
    'servicesPage.surgery.urinaryTitle': 'عمليات المسالك البولية:',
    'servicesPage.surgery.urinary': 'نُعالج مجموعة من حالات المسالك البولية، بما في ذلك حصوات المثانة وانسداد المسالك البولية ومشاكل الجهاز البولي الأخرى. تهدف هذه الإجراءات إلى استعادة وظائف المسالك البولية الطبيعية وتخفيف الانزعاج.',
    'servicesPage.surgery.closing': 'قبل أي إجراء جراحي للحيوانات الأليفة، نُجري تقييمًا شاملاً قبل الجراحة، يشمل فحصًا بدنيًا وتحاليل للدم واختبارات أخرى ضرورية، للتأكد من أن حيوانك الأليف مُرشّح جيد للجراحة. نناقش الإجراء والمخاطر المحتملة وتعليمات الرعاية بعد العملية معك بدقة. نُعطي الأولوية لإدارة الألم طوال العملية الجراحية ونوفر رعاية شاملة بعد العملية لضمان تعافي سلس ومريح. تُعدّ خدمات عيادة الجراحة البيطرية جزءًا حيويًا من التزامنا بتوفير رعاية كاملة وحانية لحيوانك الأليف.',
    
    // Dental Services
    'servicesPage.dental.title': 'خدمات طب الأسنان',
    'servicesPage.dental.description': 'تُعدّ صحة الفم الجيدة أمرًا بالغ الأهمية لصحة ورفاهية حيوانك الأليف بشكل عام. يُقدّم د. باوز خدمات بيطرية شاملة للأسنان مُصمّمة للحفاظ على صحة أسنان ولثة حيوانك الأليف طوال حياته. تشمل خدماتنا:',
    'servicesPage.dental.cleaningTitle': 'تنظيف الأسنان الاحترافي (الوقاية):',
    'servicesPage.dental.cleaning': 'يُعدّ هذا حجر الزاوية في الرعاية الوقائية للأسنان. خلال التنظيف الاحترافي، نزيل تراكم البلاك والجير من فوق وتحت خط اللثة باستخدام أدوات مُخصّصة. تُساعد هذه العملية في منع أمراض اللثة، وهي حالة خطيرة يُمكن أن تُؤدّي إلى فقدان الأسنان والألم وحتى تلف الأعضاء. نُلمّع الأسنان أيضًا لإنشاء سطح أملس أقل عُرضة لتراكم البلاك.',
    'servicesPage.dental.examinationsTitle': 'الفحوصات الشاملة للأسنان (فحوصات الفم):',
    'servicesPage.dental.examinations': 'تُعدّ الفحوصات المنتظمة للأسنان ضرورية للكشف المُبكّر عن مشاكل الأسنان. خلال هذه الفحوصات، يُقيّم أطباؤنا صحة فم حيوانك الأليف بدقة، ويتحققون من علامات أمراض اللثة وتسوس الأسنان وأورام الفم وغيرها من التشوهات. قد نوصي أيضًا بأشعة سينية للأسنان لتقييم صحة جذور الأسنان وهياكل العظام المُحيطة بها.',
    'servicesPage.dental.scalingTitle': 'كشط وتنعيم الجذور:',
    'servicesPage.dental.scaling': 'يُزيل الكشط تراكم الجير من سطح السن فوق وتحت خط اللثة، ويُنعّم تنعيم الجذور أسطح جذور الأسنان، مما يصعب على البلاك الالتصاق. يُعدّ هذا الإجراء مُهمًا بشكل خاص لعلاج أمراض اللثة ومنع المزيد من التلف للثة والعظام الداعمة.',
    'servicesPage.dental.extractionTitle': 'خلع الأسنان:',
    'servicesPage.dental.extraction': 'في حالات أمراض الأسنان الشديدة مثل أمراض اللثة المُتقدّمة أو كسور الأسنان، قد يكون الخلع ضروريًا. يُجري أطباؤنا عمليات الخلع بعناية دقيقة مع الاهتمام بإدارة الألم وراحة المريض.',
    'servicesPage.dental.surgeryTitle': 'جراحة الفم:',
    'servicesPage.dental.surgery': 'للحالات الأكثر تعقيدًا مثل أورام الفم أو كسور الفك، نقدم إجراءات جراحة فم مُتقدّمة.',
    'servicesPage.dental.closing': 'تُعدّ العناية المنتظمة بالأسنان، بما في ذلك التنظيف الاحترافي والرعاية المنزلية، ضرورية لمنع أمراض اللثة التي يُمكن أن تُؤدّي إلى مشاكل صحية خطيرة تُؤثّر على القلب والكلى والأعضاء الأخرى. صُمّمت خدماتنا البيطرية للحفاظ على صحة فم حيوانك الأليف، وتحسين جودة حياته، وتعزيز رفاهيته بشكل عام.',
    
    // Vaccinations
    'servicesPage.vaccination.title': 'التطعيمات الدورية',
    'servicesPage.vaccination.description': 'تُعدّ تطعيمات الحيوانات الأليفة حجر الزاوية في الخدمات البيطرية الوقائية، حيث تحمي حيوانك الأليف من مجموعة من الأمراض المُعدية التي يُحتمل أن تُهدّد حياته. عيادة تطعيم الحيوانات الأليفة في د. باوز، نتفهم أن كل حيوان أليف فريد من نوعه، لذلك نُخصّص بروتوكولات تطعيماتنا بناءً على نوع حيوانك وعمره ونمط حياته وعوامل الخطر الفردية.',
    'servicesPage.vaccination.catTripleTitle': 'تطعيمات القطط الثلاثي والرباعي',
    'servicesPage.vaccination.catTripleDesc': 'تعتبر التطعيمات الثلاثية والرباعية من أهم التطعيمات التي يجب أن يحصل عليها القط لحمايته من مجموعة من الأمراض الفيروسية الخطيرة. يتكون التطعيم الثلاثي من حماية ضد ثلاثة أمراض هي:',
    'servicesPage.vaccination.catTriple': 'مرض الهربس: يسبب التهابًا في الجهاز التنفسي العلوي للقطط، وقد يؤدي إلى مشاكل صحية خطيرة. • مرض الكالسيفايروس: يسبب أيضًا التهابًا في الجهاز التنفسي العلوي، وقد يتسبب في مشاكل تنفسية مزمنة. • البانليفوبينيا: يُعرف أيضًا بطاعون القطط، وهو مرض فيروسي شديد العدوى يصيب الجهاز الهضمي ويسبب الإسهال والقيء والجفاف، وقد يكون قاتلاً.',
    'servicesPage.vaccination.catQuad': 'أما التطعيم الرباعي، فهو إضافة إلى التطعيم الثلاثي حماية ضد مرض لوكيميا القطط، وهو مرض سرطاني يصيب الجهاز المناعي للقطط.',
    'servicesPage.vaccination.catBenefitsTitle': 'فوائد التطعيم الثلاثي والرباعي:',
    'servicesPage.vaccination.catBenefits': 'الحماية من الأمراض القاتلة: يحمي هذا التطعيم القطط من أمراض قد تكون قاتلة أو تسبب مضاعفات صحية خطيرة. • تقوية جهاز المناعة: يساعد هذا التطعيم على تقوية جهاز المناعة لدى القطط، مما يجعلها أكثر مقاومة للأمراض. • الوقاية من انتشار الأمراض: يساعد هذا التطعيم على منع انتشار الأمراض بين القطط الأخرى.',
    'servicesPage.vaccination.dogPentaTitle': 'تطعيم الكلاب الخماسي',
    'servicesPage.vaccination.dogPentaDesc': 'يعتبر التطعيم الخماسي من أهم التطعيمات التي يجب أن يحصل عليها الكلب لحمايته من مجموعة من الأمراض الفيروسية والبكتيرية الخطيرة. يتكون التطعيم الخماسي من حماية ضد خمسة أمراض:',
    'servicesPage.vaccination.dogPenta': 'داء السُعار: مرض فيروسي خطير يصيب الجهاز العصبي ويؤدي إلى الوفاة. • داء البارفو: مرض فيروسي شديد العدوى يصيب الجهاز الهضمي ويسبب الإسهال والقيء والجفاف، وقد يكون قاتلاً. • داء الأدنو الفيروسي: يسبب التهابًا في الجهاز التنفسي والجهاز الهضمي. • داء البارافلو: يسبب التهابًا في الجهاز الهضمي. • داء البورديتيلا: يسبب التهابًا في الجهاز التنفسي.',
    'servicesPage.vaccination.dogBenefitsTitle': 'فوائد التطعيم الخماسي:',
    'servicesPage.vaccination.dogBenefits': 'الحماية من الأمراض القاتلة: يحمي هذا التطعيم الكلاب من أمراض قد تكون قاتلة أو تسبب مضاعفات صحية خطيرة. • تقوية جهاز المناعة: يساعد هذا التطعيم على تقوية جهاز المناعة لدى الكلاب، مما يجعلها أكثر مقاومة للأمراض. • الوقاية من انتشار الأمراض: يساعد هذا التطعيم على منع انتشار الأمراض بين الكلاب الأخرى.',
    'servicesPage.vaccination.rabiesTitle': 'تطعيم السعار',
    'servicesPage.vaccination.rabies': 'يعتبر تطعيم السعار من أهم التطعيمات التي يجب أن يحصل عليها كل من الكلاب والقطط، حيث يحمي هذا التطعيم من مرض السعار وهو مرض فيروسي يصيب الجهاز العصبي ويؤدي إلى الوفاة. يمكن أن ينتقل مرض السعار إلى الإنسان عن طريق عضة حيوان مصاب، لذلك فإن تطعيم الحيوانات الأليفة هو وسيلة مهمة لمنع انتشار هذا المرض.',
    'servicesPage.vaccination.dewormTitle': 'تطعيمات الديدان',
    'servicesPage.vaccination.deworm': 'تطعيمات الديدان ليست بالضبط تطعيمات، بل هي أدوية تستخدم للقضاء على الديدان المعوية التي قد تصيب الحيوانات الأليفة. يجب إعطاء هذه الأدوية بشكل دوري حسب توجيهات الطبيب البيطري، خاصة للحيوانات التي تخرج إلى الخارج أو التي تتلامس مع حيوانات أخرى.',
    
    // Travel
    'servicesPage.travel.title': 'إجراءات سفر الحيوانات الأليفة',
    'servicesPage.travel.description': 'يُمكن أن يكون السفر مع حيوانك الأليف تجربة مُجزية، ولكنه يتطلب تخطيطًا دقيقًا والالتزام بلوائح مُحدّدة. يُقدّم د. باوز خدمات شاملة لإجراءات سفر الحيوانات الأليفة لضمان سفر سلس وآمن للحيوانات الأليفة، سواء في الداخل أو دوليًا. نتفهم أن لكل وجهة متطلبات فريدة، وفريقنا ذو الخبرة هنا لإرشادك. تشمل خدماتنا البيطرية لإجراءات سفر الحيوانات الأليفة:',
    'servicesPage.travel.certificatesTitle': 'الشهادات الصحية:',
    'servicesPage.travel.certificates': 'الشهادة الصحية هي وثيقة رسمية صادرة عن طبيب بيطري مُرخّص، تُثبت أن حيوانك الأليف يتمتع بصحة جيدة وخالٍ من الأمراض المُعدية. غالبًا ما تكون هذه الشهادة مطلوبة للسفر عبر حدود الولايات أو دوليًا. سنجري فحصًا بدنيًا شاملاً لحيوانك الأليف للتأكد من استيفائه للمعايير الصحية الضرورية. تختلف المتطلبات المُحدّدة للشهادات الصحية حسب الوجهة، لذلك من الضروري الاتصال بنا قبل موعد سفرك بوقت كافٍ.',
    'servicesPage.travel.rabiesTitle': 'اختبار داء الكَلَب لأغراض السفر:',
    'servicesPage.travel.rabies': 'داء الكَلَب مرض فيروسي خطير، وتتطلب العديد من البلدان إثباتًا للتطعيم ضد داء الكَلَب و/أو اختبارًا لمعايرة داء الكَلَب للدخول. يقيس اختبار معايرة داء الكَلَب مستوى الأجسام المُضادة لداء الكَلَب في دم حيوانك الأليف، مما يُؤكّد وجود مناعة كافية. تشمل خدماتنا البيطرية إعطاء تطعيمات داء الكَلَب (إذا لزم الأمر) وإجراء اختبار معايرة داء الكَلَب. سنُزوّدك بالوثائق الرسمية المطلوبة للسفر الدولي، مع ضمان استيفائها للمتطلبات المُحدّدة لبلد وجهتك. يُرجى ملاحظة أنه غالبًا ما تكون هناك فترات انتظار بعد التطعيم أو الاختبار قبل السماح بالسفر.',
    'servicesPage.travel.formsTitle': 'ملء نماذج الشهادات:',
    'servicesPage.travel.forms': 'يُمكن أن تكون الأوراق المطلوبة لسفر الحيوانات الأليفة دوليًا مُعقّدة ومُربكة، حيث أن للبلدان المختلفة نماذج ومتطلبات مختلفة. يُمكن لفريقنا ذي الخبرة مُساعدتك في ملء نماذج الشهادات الضرورية بدقة وكفاءة. نبقى على اطلاع دائم بأحدث اللوائح لمُختلف الوجهات، بما في ذلك الدول الأوروبية وتلك التي تتطلب شهادات مُصدّقة مُحدّدة من APHIS USDA (وزارة الزراعة الأمريكية، خدمة فحص صحة الحيوان والنبات). سنضمن ملء جميع النماذج وتصديقها بشكل صحيح، مما يُقلّل من خطر التأخير أو المُضاعفات أثناء سفرك.',
    'servicesPage.travel.closing': 'صُمّمت هذه الخدمات البيطرية لإجراءات سفر الحيوانات الأليفة لجعل العملية خالية من التوتر قدر الإمكان لك ولحيوانك الأليف. نوصي بالاتصال بنا قبل أسابيع أو حتى أشهر من موعد سفرك المُخطّط له لإتاحة وقت كافٍ للفحوصات والاختبارات والأوراق الضرورية.',
    
    // Boarding
    'servicesPage.boarding.title': 'خدمات الإقامة',
    'servicesPage.boarding.description': 'في د. باوز، نتفهم أن ترك حيوانك الأليف قد يكون مُرهقًا. لهذا السبب نُقدّم خدمات الإقامة وفندقة الحيوانات المُريحة والرعاية كجزء من خدماتنا البيطرية الشاملة. نُلبي مجموعة مُتنوعة من الاحتياجات مع خيارات إقامة مُتخصّصة:',
    'servicesPage.boarding.therapeuticTitle': 'فندق علاجي للحيوانات الأليفة:',
    'servicesPage.boarding.therapeuticDesc': 'صُمّم فندقنا العلاجي للحيوانات الأليفة التي تتطلب رعاية طبية مُتخصّصة خلال إقامتها. هذا الخيار مثالي لـ:',
    'servicesPage.boarding.therapeutic': 'التعافي بعد الجراحة: تتلقى الحيوانات الأليفة التي تتعافى من الإجراءات الجراحية مُراقبة دقيقة وإدارة للألم ومُساعدة في الحركة حسب الحاجة. يضمن فريقنا المُدرّب راحتها وشفائها بشكل صحيح. • إدارة الحالات المُزمنة: تتلقى الحيوانات الأليفة التي تُعاني من حالات مثل مرض السكري أو أمراض الكلى أو أمراض القلب رعاية فردية، بما في ذلك إعطاء الأدوية والأنظمة الغذائية المُتخصّصة والمُراقبة المنتظمة لحالتها. • الحيوانات الأليفة التي تتطلب مُراقبة دقيقة: تستفيد الحيوانات الأليفة التي تُعاني من حالات طبية غير مُستقرة أو تلك التي تتطلب مُلاحظة مُتكررة من الاهتمام الوثيق لفريقنا البيطري. نُراقب العلامات الحيوية ونُعطي الأدوية ونُقدّم أي علاجات ضرورية.',
    'servicesPage.boarding.antifungalTitle': 'فندق للحيوانات الأليفة وعلاج الفطريات:',
    'servicesPage.boarding.antifungal': 'صُمّم خيار الإيواء المُتخصّص هذا للحيوانات الأليفة التي تخضع لعلاج من الالتهابات الفطرية. نتفهم أهمية منع انتشار هذه الالتهابات، ولهذا السبب نُوفّر: العزل: تُوضع الحيوانات الأليفة التي تتلقى علاجًا مُضادًا للفطريات في بيئة مُنفصلة ومعزولة لمنع انتقال العدوى. • بروتوكولات تنظيف وتطهير مُتخصّصة: نلتزم ببروتوكولات صارمة للنظافة لضمان بقاء البيئة نظيفة وخالية من الأبواغ الفطرية. • إعطاء الأدوية المُضادة للفطريات: يُعطي فريقنا المُدرّب الأدوية المُضادة للفطريات الموصوفة وفقًا لتعليمات الطبيب البيطري. • مُراقبة تقدّم العلاج: نُراقب عن كثب تقدّم حيوانك الأليف طوال فترة إقامته، لضمان فعالية العلاج وإجراء التعديلات حسب الحاجة.',
    
    // Intensive Care
    'servicesPage.intensiveCare.title': 'العناية المركزة (علاج ورعاية الأمراض غير المُعدية)',
    'servicesPage.intensiveCare.description': 'في عيادة د. باوز البيطرية، نتفهم أن الأمراض والإصابات الخطيرة تتطلب رعاية مُتخصّصة. وحدة العناية المركزة للحيوانات الأليفة لدينا هي مساحة مُخصّصة داخل عياداتنا البيطرية مُصممة لتوفير مُراقبة وعلاج مُتقدّمين للحيوانات الأليفة في الحالات التي تُهدّد حياتها. فريقنا البيطري مُدرّب على طب الحالات الحرجة ويستخدم أحدث المُعدّات لتوفير رعاية على مدار الساعة. تُركّز خدمات مركز العناية بالحيوانات الأليفة لدينا على إدارة وعلاج مجموعة من الأمراض غير المُعدية والحالات الحرجة، بما في ذلك:',
    'servicesPage.intensiveCare.organ': 'فشل الأعضاء: الفشل الكلوي: نُوفّر علاجًا مُتقدّمًا بالسوائل وإدارة للكهارل ورعاية داعمة أخرى لإدارة الفشل الكلوي الحاد والمُزمن. • الفشل الكبدي: يُقدّم فريقنا علاجات مُتخصّصة لدعم وظائف الكبد وإدارة المُضاعفات ومعالجة الأسباب الكامنة وراء أمراض الكبد. • فشل القلب: نُقدم مُراقبة مُتقدّمة للقلب وعلاجًا بالأكسجين وإدارة للأدوية لتثبيت حالة الحيوانات الأليفة المُصابة بفشل القلب وتحسين جودة حياتها.',
    'servicesPage.intensiveCare.metabolic': 'الاضطرابات الأيضية: نُدير الحالات الأيضية المُعقّدة مثل داء السكري ومرض كوشينغ ومرض أديسون من خلال المُراقبة الدقيقة وتعديلات الأدوية والدعم الغذائي.',
    'servicesPage.intensiveCare.endocrine': 'أمراض الغدد الصماء: نُوفّر رعاية مُتخصّصة للحيوانات الأليفة المُصابة باضطرابات الغدد الصماء، بما في ذلك قصور الغدة الدرقية وفرط نشاط الغدة الدرقية والسكري الكاذب. يعمل فريقنا على تنظيم مُستويات الهرمونات وإدارة الأعراض المُصاحبة.',
    'servicesPage.intensiveCare.trauma': 'الإصابات الشديدة: نُوفّر رعاية فورية وشاملة للحيوانات الأليفة المُصابة بإصابات رضحية، بما في ذلك الكسور والإصابات الداخلية والجروح الشديدة. تشمل خدماتنا إدارة الألم والتثبيت والتدخل الجراحي عند الضرورة.',
    'servicesPage.intensiveCare.postSurgical': 'حالات حرجة أخرى: مركز العناية بالحيوانات لدينا مُجهز أيضًا للتعامل مع حالات حرجة أخرى، مثل: الالتهابات الشديدة (الإنتان) • ضيق التنفس • الحالات العصبية • مُضاعفات ما بعد الجراحة',
    
    // Emergency
    'servicesPage.emergency.title': 'خدمات الطوارئ',
    'servicesPage.emergency.description': 'يُمكن أن تكون حالات الطوارئ للحيوانات الأليفة تجربة مُخيفة. في د. باوز، نتفهم مدى إلحاح وضغط هذه المواقف. نُقدّم خدمات بيطرية من خلال عيادة بيطرية طوارئ ٢٤ ساعة للحيوانات الأليفة، وفريقنا المُتخصّص مُستعد للتعامل مع مجموعة واسعة من الحالات الطبية الطارئة. بعض الأمثلة على حالات الطوارئ التي نُعالجها تشمل:',
    'servicesPage.emergency.trauma': 'الصدمات (الاصطدام بسيارة، السقوط): تتطلب الإصابات الناجمة عن حوادث السيارات أو السقوط أو غيرها من الأحداث الرضحية عناية بيطرية فورية. نحن مُجهّزون لتقييم وعلاج الكسور والإصابات الداخلية والحالات الأخرى المُتعلّقة بالصدمات.',
    'servicesPage.emergency.breathing': 'صعوبة التنفس: يُمكن أن يكون ضيق التنفس حالة طارئة تُهدّد الحياة. إذا كان حيوانك الأليف يُعاني من صعوبة في التنفس أو يلهث بحثًا عن الهواء أو لديه لثة زرقاء اللون، فاطلب رعاية بيطرية فورية.',
    'servicesPage.emergency.bleeding': 'نزيف حاد: يتطلب النزيف غير المُسيطر عليه، سواء كان داخليًا أو خارجيًا، تدخلاً بيطريًا سريعًا لمنع المزيد من المُضاعفات.',
    'servicesPage.emergency.seizures': 'التسمم: يُمكن أن يُسبب ابتلاع مواد سامة مجموعة مُتنوعة من الأعراض الخطيرة. إذا كنت تشك في أن حيوانك الأليف قد ابتلع سمًا، فاتصل بنا أو بخط المُساعدة الخاص بالتسمم للحيوانات الأليفة على الفور. • النوبات: يُمكن أن تكون النوبات علامة على مشاكل عصبية أو أيضية كامنة. إذا أُصيب حيوانك الأليف بنوبة، فمن المُهم طلب رعاية بيطرية لتحديد السبب والعلاج المُناسب. • الانتفاخ (توسع المعدة والالتواء): تُعدّ هذه الحالة التي تُهدّد الحياة، الشائعة في الكلاب من السلالات الكبيرة، انحشار المعدة بالغاز والتواءها. التدخل البيطري الفوري أمر بالغ الأهمية.',
    'servicesPage.emergency.numbers': 'إذا كان حيوانك الأليف يُعاني من أي من هذه المشاكل الطبية الطارئة أو غيرها، فيُرجى الاتصال بقسم الطوارئ للحيوانات الأليفة على الفور على:',
    'servicesPage.emergency.sahafa': 'طوارئ فرع الصحافة: 05520 30564',
    'servicesPage.emergency.mather': 'طوارئ فرع المعذر: 05313 53667',
    'servicesPage.emergency.closing': 'سيُقدّم فريق الطوارئ للحيوانات الأليفة لدينا إرشادات ويستعد لوصولك. هدفنا من خدمات الطوارئ البيطرية هو توفير رعاية سريعة وفعّالة عندما يكون حيوانك الأليف في أمس الحاجة إليها.',
    
    // Home Care
    'servicesPage.homeCare.title': 'خدمات الرعاية المنزلية',
    'servicesPage.homeCare.description': 'نتفهم أن زيارة عيادة بيطرية قد تكون صعبة بالنسبة لبعض الحيوانات الأليفة وأصحابها. سواء كان حيوانك الأليف يُعاني من القلق أثناء السفر أو لديه مشاكل في الحركة أو كنت تُفضّل ببساطة راحة الرعاية في المنزل، يُقدّم د. باوز خدمات بيطرية للرعاية المنزلية لجلب خبرتنا إليك مُباشرةً. قد تشمل خدمات الرعاية المنزلية لدينا:',
    'servicesPage.homeCare.wellness': 'الفحوصات الصحية: يُمكننا إجراء فحوصات صحية روتينية في راحة منزلك، وتقييم صحة حيوانك الأليف بشكل عام وفحص العلامات الحيوية ومُناقشة أي مخاوف قد تكون لديك. يُعدّ هذا مُفيدًا بشكل خاص للحيوانات الأليفة الكبيرة في السن أو تلك التي تُعاني من قيود في الحركة.',
    'servicesPage.homeCare.vaccinations': 'التطعيمات: يُمكننا إعطاء التطعيمات الضرورية في المنزل، وحماية حيوانك الأليف من الأمراض التي يُمكن الوقاية منها دون ضغوط زيارة العيادة.',
    'servicesPage.homeCare.sample': 'جمع العينات: يُمكننا جمع عينات مثل الدم أو البول أو البراز في منزلك للاختبارات التشخيصية، مما يُقلّل من التوتر على حيوانك الأليف.',
    'servicesPage.homeCare.closing': 'صُمّمت خدماتنا البيطرية للرعاية المنزلية لتوفير رعاية يسهل الوصول إليها مما يضمن حصول حيوانك الأليف على الاهتمام الضروري مع تقليل التوتر لك وله. يُرجى الاتصال بنا لمُناقشة احتياجات حيوانك الأليف وتحديد ما إذا كانت الزيارة المنزلية هي الخيار المُناسب.',
    
    // Footer
    'footer.description': 'من الفحوصات الروتينية إلى الجراحات المتقدمة، تقدم د. باوز رعاية بيطرية متكاملة لجميع احتياجات حيوانك الأليف.',
    'footer.contactInfo': 'معلومات التواصل',
    'footer.call': 'الاتصال',
    'footer.generalPhone': '920003045',
    'footer.emergency': 'الطوارئ: متوفرون لخدمتكم على مدار الساعة طوال أيام الأسبوع',
    'footer.mobile': 'جوال',
    'footer.sahafahBranch': 'فرع الصحافة',
    'footer.sahafahAddress': 'عيادة د. باوز البيطرية، طريق الثمامة، حي الصحافة، الرياض 13315',
    'footer.sahafahPhone': '0552030564',
    'footer.sahafahMapUrl': 'https://www.google.com/maps/search/?api=1&query=Dr.Paws+Veterinary+Clinic,Al+Thoumamah+Rd,As+Sahafah,Riyadh+13315',
    'footer.matherBranch': 'فرع المعذر',
    'footer.matherAddress': 'عيادة د. باوز البيطرية، طريق الأمير سلطان بن عبدالعزيز، المعذر الشمالية، الرياض 12314',
    'footer.matherPhone': '0531353667',
    'footer.matherMapUrl': 'https://www.google.com/maps/search/?api=1&query=Dr.Paws+Veterinary+Clinic,Prince+Sultan+Bin+Abdulaziz+Rd,Al+Mathar+Ash+Shamali,Riyadh+12314',
    'footer.hours': 'ساعات العمل',
    'footer.satThu': 'من السبت إلى الخميس: من 9:00 صباحًا حتى 10:00 مساءً',
    'footer.fri': 'يوم الجمعة: من 3:00 مساءً حتى 10:00 مساءً',
    'footer.email': 'info@drpaws-sa.com',
    'footer.follow': 'تابعنا',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    // Set RTL direction and lang attribute when language changes
    if (language === 'ar') {
      document.documentElement.setAttribute('dir', 'rtl');
      document.documentElement.setAttribute('lang', 'ar');
    } else {
      document.documentElement.setAttribute('dir', 'ltr');
      document.documentElement.setAttribute('lang', 'en');
    }
  }, [language]);

  const t = (key: string): string => {
    const translationKey = key as keyof typeof translations['en'];
    if (translationKey in translations[language]) {
      return translations[language][translationKey] as string;
    }
    if (translationKey in translations.en) {
      return translations.en[translationKey] as string;
    }
    return key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
